name: Static Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Start Containers
      run: docker compose up -d --build

    - name: Install Dependencies
      run: docker compose exec app bash -c "cd ./project && /etc/poetry/bin/poetry install"

    - name: Formatting Test (Run)
      run: docker compose exec app bash -c "cd ./project && /etc/poetry/bin/poetry run black project tests"

    - name: Formatting Test (Evaluate)
      run: |
        git diff --exit-code || (echo 'Failed: Run `poetry run black`' && exit 1)

    - name: Lint
      run: docker compose exec app bash -c "cd ./project && /etc/poetry/bin/poetry run flake8 project tests"

    - name: Static Analysis
      run: docker compose exec app bash -c "cd ./project && /etc/poetry/bin/poetry run mypy project"
